export const projectsData = [
  {
    id: 1,
    title: 'Full-Stack Weather app',
    description: 'A widget style appliction that display current weather',
    features: [
      'Using Geolocation in the Browser',
      'Fetching data from an API on the Backend and serving it to the front',
      'Private backend server in express to avoid CORS',
      'Using custom weather icons from a separate module',
    ],
    githubLink: 'https://github.com/develad/weather-fullstack',
    websiteLink: 'https://weather-vanilla.netlify.app/',
    img: ['/images/weatherCard.png'],
    isMobile: true,
  },
  {
    id: 2,
    title: 'Beer app',
    description: 'A Beer Trivia info appliction that interact with the user',
    features: [
      'Fully React js appliction using Hooks and functional components',
      'Fetching data from an API using Async/Await',
      'Filtering User input data and displying it to the DOM',
      'Advanced css for friendly UI',
    ],
    githubLink: 'https://github.com/develad/beer-app',
    websiteLink: 'https://develad.github.io/beer-app/',
    img: ['/images/beerCard.png'],
    isMobile: true,
  },
  {
    id: 3,
    title: 'Personal portfolio site',
    description: 'My personal portfolio site Fully made with REACT JS by me',
    features: [
      'Fully React js appliction',
      'Styled ONLY with Styled Components 💅',
      'Animation with framer-motion',
      'Reusable components',
      'Form handeling',
      'Advanced css for a friendly UI',
    ],
    githubLink: 'https://github.com/develad/Portfolio',
    websiteLink: 'https://elad-bar-portfolio.netlify.app/',
    img: ['/images/profileSite.png', '/images/profileSite.png'],
    isMobile: true,
  },
  {
    id: 4,
    title: 'Super Mario Clock 🕗',
    description: 'A Vanilla JS Super Mario Clock Screen Saver',
    features: [
      'Simple Beginner project to practise web development fundamentals',
      'Can be used as a Screen saver 👾',
      'Displaying current time',
      'small interaction with animation',
    ],
    githubLink: 'https://github.com/develad/super-mario-clock',
    websiteLink: 'https://super-mario-clock.netlify.app/',
    img: ['/images/superMario.png'],
    isMobile: true,
  },
  {
    id: 5,
    title: 'hover board',
    description:
      'A Drawing HoverBoard in Pixel Art style developed for the Desktop web browser in Vanilla js',
    features: [
      'Managing user Interactions',
      'using Advanced Css techniques to form a drawing Grid',
      'using Font Awesome Custom Icons via cdn',
    ],
    githubLink: 'https://github.com/develad/hover-board-new',
    websiteLink: 'https://hover-board-new.netlify.app/',
    img: ['/images/hoverBoard.png'],
    isMobile: false,
  },
];
